name: Generate Tech Stack Cube  
on:
  # Run weekly on Sunday
  schedule:
    - cron: '0 0 * * 0'
  # Run on push to main branch
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:
jobs:
  generate-tech-stack-svg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Generate Tech Stack Cube SVG
      run: node .github/scripts/generate-tech-stack-cube.js
    
    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tech-stack-cube.svg
        git commit -m "Update tech stack cube SVG with embedded icons" || echo "No changes to commit"
        git push
