name: Generate Tech Stack Cube

on:
  # Run on pushes to main branch
  push:
    branches: [ main ]
  # Run on schedule (every day at midnight)
  schedule:
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm install puppeteer @svgdotjs/svg.js

    - name: Generate Tech Stack Cube SVG
      run: node generate-tech-stack-cube.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tech-stack-cube.svg
        git commit -m "Update tech stack cube" || echo "No changes to commit"
        git push
