name: Generate Tech Stack Cube

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  
  # Run on schedule (once a day)
  schedule:
    - cron: '0 0 * * *'
    
  # Run on pushes to main branch
  push:
    branches: [ main ]

jobs:
  generate-tech-stack:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: |
          npm install puppeteer
          npm install @svgdotjs/svg.js
      
      - name: Generate Tech Stack Cube SVG
        run: node .github/scripts/generate-tech-stack-cube.js
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Commit and Push SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'tech-stack-cube.svg'
          message: 'Update tech stack cube SVG'
          default_author: github_actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
