name: Update Visitor Counter
on:
  schedule:
    # Run every hour for more frequent updates
    - cron: '0 */1 * * *'
  workflow_dispatch:  # Allows manual triggering
  # Add this to update when README changes
  push:
    paths:
      - 'README.md'

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history to ensure we have the counter history
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Update visitor counter
        run: |
          python .github/scripts/update_counter.py
          
      - name: Commit changes if any
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add visitor-counter.svg counter_analytics.csv last_check.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update visitor counter [skip ci]"
          git push
